version: "3.9"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=todo_db
      - "TZ= Asia/Tokyo"
    volumes:
      - ./Backend:/app
      - /etc/localtime:/etc/localtime:ro
    networks:
      - todo-net

  db:
    image: postgres:17.2
    container_name: localhost
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=todo_db
      - "TZ= Asia/Tokyo"
    volumes:
      - ReactDev:/var/lib/postgresql/data:delegated
      - ./Backend/Database/postgres:/docker-entrypoint-initdb.d

    networks:
      - todo-net

volumes:
  ReactDev:

networks:
  todo-net:
